name: ci
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [verify, test]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: make teleport-build

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        # Use version 1.19 in order to run verify-codegen.sh
        go-version: "^1.19"
        cache: true
    - name: Run Verify
      run: make teleport-verify

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
    - name: Unit Tests
      run: make teleport-test
